services:
  pingtool:
    image: tonyb486/pingtool
    build: .
    environment:
      TZ: America/New_York
      TARGET: 8.8.4.4
    ports:
      - "8000:80"
    volumes:
      - datavol:/data

volumes:
  datavol:
